jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        PYTHON_VERSION: '2.7'
      Python34:
        PYTHON_VERSION: '3.4'    
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'    
      Python36:
        PYTHON_VERSION: '3.6'          
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
    displayName: 'Install Python'
  - script: install make
    displayName: 'Install Make'
  - script: |
      make test-readme
      make ci
 - ${{ if eq(PYTHON_VERSION, '3.6') }}:
    - script: |
        codecov
    - displayName: 'Coverage'
