jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python27:
        PYTHON_VERSION: '2.7'
      Python34:
        PYTHON_VERSION: '3.4'    
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'    
      Python37:
        PYTHON_VERSION: '3.7'          
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      architecture: 'x64'
    displayName: 'install Python'
  - script: |
      make
      pipenv install -e .[socks] --skip-lock 
    displayName: 'setup'
  - script: |
      make test-readme
    displayName: 'test-readme'
  - script: |
      make ci
    displayName: 'ci'        
  - script: |
      make coverage
    displayName: 'coverage'    
  - script: |
      pipenv run codecov -f coverage.xml
    displayName: 'run codecov'
  - task: PublishTestResults@2
    displayName: 'publish test results'
    inputs:
      testResultsFiles: 'report.xml'
      testRunTitle: Python $(PYTHON_VERSION)    
